# ~/.tmuxinator/config.yml

name: config
root: ~/.vimconfig

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

windows:
  - default:
      layout: a82b,179x50,0,0{89x50,0,0,2,89x50,90,0[89x25,90,0,3,89x24,90,26,4]}
      panes:
        - vim default/settings.vim
        - vim default/plugins.vim
        - vim default/mappings.vim
  - c++:
      layout: a82b,179x50,0,0{89x50,0,0,2,89x50,90,0[89x25,90,0,3,89x24,90,26,4]}
      panes:
        - vim c++/settings.vim
        - vim c++/plugins.vim
        - vim c++/mappings.vim
  - latex:
      layout: a82b,179x50,0,0{89x50,0,0,2,89x50,90,0[89x25,90,0,3,89x24,90,26,4]}
      panes:
        - vim latex/settings.vim
        - vim latex/plugins.vim
        - vim latex/mappings.vim
  - python:
      layout: a82b,179x50,0,0{89x50,0,0,2,89x50,90,0[89x25,90,0,3,89x24,90,26,4]}
      panes:
        - vim python/settings.vim
        - vim python/plugins.vim
        - vim python/mappings.vim
