# ~/.tmuxinator/config.yml

name: config
root: ~/github/dotfiles

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

windows:
  - vimrc:
      panes:
        - vim _vimrc
  - default:
      layout: a82b,179x50,0,0{89x50,0,0,2,89x50,90,0[89x25,90,0,3,89x24,90,26,4]}
      panes:
        - vim _vimconfig/default/settings.vim
        - vim _vimconfig/default/plugins.vim
        - vim _vimconfig/default/mappings.vim
  - c++:
      layout: a82b,179x50,0,0{89x50,0,0,2,89x50,90,0[89x25,90,0,3,89x24,90,26,4]}
      panes:
        - vim _vimconfig/c++/settings.vim
        - vim _vimconfig/c++/plugins.vim
        - vim _vimconfig/c++/mappings.vim
  - latex:
      layout: a82b,179x50,0,0{89x50,0,0,2,89x50,90,0[89x25,90,0,3,89x24,90,26,4]}
      panes:
        - vim _vimconfig/latex/settings.vim
        - vim _vimconfig/latex/plugins.vim
        - vim _vimconfig/latex/mappings.vim
  - python:
      layout: a82b,179x50,0,0{89x50,0,0,2,89x50,90,0[89x25,90,0,3,89x24,90,26,4]}
      panes:
        - vim _vimconfig/python/settings.vim
        - vim _vimconfig/python/plugins.vim
        - vim _vimconfig/python/mappings.vim
  - color:
      panes:
        - vim ~/github/vim-mudcrab/colors/mudcrab.vim
